//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface ECConfig : NSObject
- (BOOL)runningInVM; //噶撸妈急
@end

@interface ACMSManager : NSObject

@property BOOL runningInVM;//噶撸妈急

@end
